language: python
python:
- '2.7'
install: pip install --upgrade pip && pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database menu_test;' -U postgres
script: python manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
